name: flutter_design_patterns
description: A collection of Design Pattern implementations in Dart programming language.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.0-271.7.beta <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  easy_localization: ^3.0.1
  equatable: ^2.0.5
  flex_color_scheme: ^5.1.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^1.0.4
  go_router: ^4.3.0
  google_fonts: ^3.0.1
  shared_preferences: ^2.0.15

flutter:
  uses-material-design: true

  assets:
    - assets/languages/
    - assets/images/
    - assets/fonts/